[FileDialog]
history=file:///home/jade/Pictures, file:///home/jade/.config/hypr, file:///home/jade/.local/share/PrismLauncher/instances/Ultimate PVP Client/minecraft/resourcepacks/\xa7\x62Glacier 16x )\xa7\x66[Defrost]/assets/minecraft/textures/items, file:///home/jade/.local/share/PrismLauncher/instances/Ultimate PVP Client/minecraft/resourcepacks/\xa7l\xa7\x62\x46rozen\xa7\x36Nut/assets/minecraft/textures/items, file:///home/jade/.local/share/PrismLauncher/instances/Meownumenta/minecraft/screenshots
lastVisited=file:///home/jade/.local/share/PrismLauncher/instances/Meownumenta/minecraft/screenshots
qtVersion=5.15.17
shortcuts=file:, file:///home/jade
sidebarWidth=116
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2O\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1:\0\0\0\x1\0\0\0\0\0\0\0H\0\0\0\x1\0\0\0\0\0\0\0M\0\0\0\x1\0\0\0\0\0\0\0\x80\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
