[FileDialog]
history=file:///home/jade/.local/share/PrismLauncher/instances/Ultimate PVP Client/minecraft/resourcepacks/\xc2\xa7l\xc2\xa7\x62\x46rozen\xc2\xa7\x36Nut/assets/minecraft/textures/items, file:///home/jade/.local/share/PrismLauncher/instances/Meownumenta/minecraft/screenshots, file:///home/jade, file:///home/jade/.config/Kvantum, file:///home/jade/Pictures
lastVisited=file:///home/jade/Pictures
qtVersion=5.15.17
shortcuts=file:, file:///home/jade
sidebarWidth=116
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2O\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1:\0\0\0\x1\0\0\0\0\0\0\0H\0\0\0\x1\0\0\0\0\0\0\0M\0\0\0\x1\0\0\0\0\0\0\0\x80\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
